# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2b5b789aadb7deb1b1e67876766fc6632e60c244c6c7bf25b23e001f1bdf16b93d86b9ede3c2c754845221729b0aa494d94560021b36a77d72515a01a2ef17c

test:
  secret_key_base: e45cc5a53cf75a120db083e1b270461922d67b955b7221e8fb90061636e973f26c8201e1b12e03b7da6eefe47a4ba296e30a2e23e9c4bddd0b4034d97a8295c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
